### PR TITLE
Unit test group refactor

### PR DESCRIPTION
**Pull request by Sqeaky**
This PR is not quite ready yet, but I am preparing it to see CI results.

### CODE REVIEW

**Comment by Sqeaky** [comment]
I can't use std::regex, because its not implemented on the old compilers supported by appveyor and  travis

**Comment by MakoEnergy** [comment]
I know this is still in progress, but my thoughts/comments thus far:
1) In the AutomaticTestGroup header, the public access specifier and destructor are indented one tab further than we have discussed previously.  Also the destructor isn't documented.  Does Doxygen conditionally not care for docs?
2) In the BenchmarkTestGroup header...all the same complaints as "1)".  Plus some extra non-documented methods.
3) In the InteractiveTestGroup header...all the same complaints as "1)" and "2)".
4) In the SilentTestGroup header...all the same complaints as "1)", "2)", and "3)".

That's it from the first pass.  I'll do another pass before ok'ing it.

**Comment by MakoEnergy** [comment]
I have made a commit of my own fixing a bunch of documentation errors and styling oddities I found.  You should review the commit yourself.  

Additionally, in MezzTest.h/.cpp, in the MainImplementation method you pass in the UnitTestGroup parameter by reference (not const), but in the body of the method it only gets passed into one other method, which takes it as const.  Can this parameter be made const?

**Comment by MakoEnergy** [comment]
Oh, and while I was doing my commit a couple of the fixes I made were mismatches between the parameter name and it's documented name.  And one of the parameters was simply undocumented in the MainImplementation documentation.  Is this an error, or do I misunderstand our doxygen integration?

**Comment by Sqeaky** [comment]
I must not have had doxygen enabled, I also thought clang would have caught it. I will re-run doxygen and fix all its warnings before suggesting we merge.

**Pull request merged**
