### PR TITLE
Copyrights, grammar, perfecting.

### PR DESCRIPTION
**Pull request by hlayne35**
Also removed some old commented-out code per Sqeaky's request.

### CODE REVIEW

**Comment by hlayne35** [comment]
I will find the merge conflicts.

**Comment by Sqeaky** [comment]
In CMakeLists.txt you added periods to the ends of lines that are intended to serve as code examples or as alternative implementations. The non-examples should be removed, and periods make code examples incorrect.

**Comment by Sqeaky** [comment]
Other than the CMakeLists.txt all the changes look good to me.

**Comment by MakoEnergy** [comment]
Putting periods at the end of the comments meant to divide sections of functionality looks really, really weird to me.  Normal comments it's find, but the dividers are like headers for sections in an english or research paper and you don't put periods in those.

Otherwise this looks good.

**Comment by hlayne35** [comment]
I tried to keep periods to just ones that look like sentences, I'm sorry.  I can remove them from anything that you want.  I will re-examine them now.

**Comment by Sqeaky** [comment]
I am fine with  periods a the end of any English sentence. I could go either way one "headers" because not all titles are sentences. I don't care enough to hold back a PR with other perfectives.

**Comment by MakoEnergy** [comment]
Half of them aren't sentences, near as I can tell.  The other half happen to be sentences despite being section titles/dividers.  This seems like it would be a simple fix and in line with a "perfective" patch.

**Comment by Sqeaky** [comment]
Cool, I wasn't trying to argue, just stating my neutrality.

**Comment by Sqeaky** [comment]
Closing stale

**Pull request closed without merging**
